spring:
  application:
    name: Vibe Studio
    description: this is application

  datasource:
    url: jdbc:postgresql://localhost:5432/vibe_studio
    username: postgres
    password: Dilip@1586
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret-key: as9b7aodlbjfkluosfd789ujeklfnlsduf90b8ha908w74tuqijvlckajdl

stripe:
  secret: ${STRIPE_SECRET_KEY}
#  secret: sk_test_51ReZ5jRl21PQC0VyizRuRUdDKJyTAshaVT96OsZYGMRToQ405xWjw268ycZOQD80048zazwfMT4FUvf0SsuukF8z00FukHYpYs
  webhook:
    secret:

client.url: http://localhost:8080